server:
  port: 8082

spring:
  application:
    name: ai-service

  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY} # Cheia ta de la aistudio.google.com
        project-id: ${GOOGLE_PROJECT_ID}
        chat:
          options:
            model: gemini-2.0-flash-lite
        embedding:
          text:
            options:
              model: text-embedding-004
          api-key: ${GOOGLE_API_KEY}
          project-id: ${GOOGLE_PROJECT_ID}
#    vectorstore:
#      chroma:
#        client:
#          host: http://localhost
#          port: 8000
#        initialize-schema: false
#        collection-name: library_collection

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/