server:
  port: 8082

spring:
  application:
    name: ai-service

  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver

  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY} # Cheia ta de la aistudio.google.com
        project-id: ${GOOGLE_PROJECT_ID}
        chat:
          options:
            model: gemini-2.0-flash-lite
        embedding:
          text:
            options:
              model: text-embedding-004
          api-key: ${GOOGLE_API_KEY}
          project-id: ${GOOGLE_PROJECT_ID}
    # Configurare Vector Store (PgVector)
    vectorstore:
      pgvector:
        # Gemini folosește 768 dimensiuni (Default PGVector e 1536 pt OpenAI)
        dimensions: 768
        index-type: HNSW # Cel mai rapid tip de indexare
        distance-type: COSINE_DISTANCE
        initialize-schema: true # Va crea automat tabela vector_store

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/